
// tag::DE[]
[[LG-01-03]]
==== LZ 01-03: Langfristige Auswirkungen von Softwarearchitektur kennen (R3)


Softwarearchitekt:innen kennen

* den Zusammenhang zwischen Architekturentscheidungen und der zukünftigen Anpassbarkeit und Wartbarkeit des Systems
* die Auswirkungen durch Änderungen von Anforderungen, Technologien oder Systemumgebung auf bestehende Architekturentscheidungen
* die langfristigen Konsequenzen von Architekturentscheidungen auf verschiedene Qualitätsmerkmale des Systems
* die Wechselwirkungen zwischen IT-Systemen und den unterstützten Geschäfts- und Betriebsprozessen

Sie wissen, wie sie die Auswirkungen von Architekturentscheidungen auf die langfristige Entwicklung eines Systems analysieren können.
// end::DE[]

// tag::EN[]
[[LG-01-03]]
==== LG 01-03: Know Long-term Impact of Software Architecture (R3)

Software architects know:

* the relationship between architectural decisions and the future adaptability and maintainability of the system
* the impact of changes in requirements, technologies or system environment on existing architectural decisions
* the long-term consequences of architectural decisions on various quality characteristics of the system
* the interdependencies between IT systems and the supported business and operational processes

They know how to analyze the impact of architectural decisions on the long-term evolution of a system.

// end::EN[]

// tag::TR[]
[[LG-01-03]]
==== LG 01-03: Yazılım Mimarisinin Uzun Vadeli Etkisini Bilmek (R3)

Yazılım mimarları şunları bilir:

* mimari kararlar ile sistemin gelecekteki uyarlanabilirliği ve bakım yapılabilirliği arasındaki ilişki
* gereksinimler, teknolojiler veya sistem ortamındaki değişikliklerin mevcut mimari kararlar üzerindeki etkisi
* mimari kararların sistemin çeşitli kalite özellikleri üzerindeki uzun vadeli sonuçları
* BT sistemleri ile desteklenen iş ve operasyonel süreçler arasındaki karşılıklı bağımlılıklar

Mimari kararların bir sistemin uzun vadeli evrimine etkisini nasıl analiz edeceklerini bilirler.

// end::TR[]

===== {references}

<<bass>>, <<lehman>>, <<lehmanwiki>>, <<lilienthal>>, <<ford>>, <<rajlich>>, <<richardsfundamentals>>