// tag::DE[]
[[LG-01-01]]
==== LZ 01-01: Definitionen von Softwarearchitektur verstehen (R1)

Softwarearchitekt:innen kennen und verstehen die Gemeinsamkeiten vieler Definitionen von Softwarearchitektur:

* {glossary_url}building-block[Komponenten/Bausteine] mit Schnittstellen und Beziehungen
* Bausteine als allgemeiner Begriff, Komponenten als eine spezielle Ausprägung davon
* Strukturen, {glossary_url}cross-cutting-concern[Querschnittsthemen], Prinzipien
* Architekturentscheidungen und ihre Auswirkungen auf das gesamte System und seinen Lebenszyklus

// end::DE[]

// tag::EN[]
[[LG-01-01]]
==== LG 01-01: Understand Definitions of Software Architecture (R1)

Software architects know and understand the commonalities of many definitions of software architecture:

* {glossary_url}building-block[components/building blocks] with interfaces and relationships
* building blocks as a general term, components as a special form thereof
* structures, {glossary_url}cross-cutting-concern[cross-cutting concerns], principles
* architecture decisions and their consequences on the entire systems and its lifecycle

// end::EN[]

// tag::TR[]
[[LG-01-01]]
==== LG 01-01: Yazılım Mimarisi Tanımlarını Anlamak (R1)

Yazılım mimarları, birçok yazılım mimarisi tanımının ortak noktalarını bilir ve anlar:

* arayüzler ve ilişkilerle birlikte {glossary_url}building-block[bileşenler/yapı taşları]
* genel bir terim olarak yapı taşları, bunların özel bir biçimi olarak bileşenler
* yapılar, {glossary_url}cross-cutting-concern[kesişimsel ilgi alanları], ilkeler
* mimari kararlar ve bunların tüm sistem ve yaşam döngüsü üzerindeki sonuçları

// end::TR[]

===== {references}
<<iso42010>>, <<bass>>, <<kruchten>>, <<starkelorz>>

