
// tag::DE[]
[[LG-01-02]]
==== LZ 01-02: Ziele und Nutzen von Softwarearchitektur verstehen und erläutern (R1)

Softwarearchitekt:innen können die folgenden wesentlichen Ziele und Nutzen der Softwarearchitektur begründen:

* Entwurf, Implementierung, Pflege und Betrieb von Systemen zu unterstützen
* funktionale Anforderungen zu erreichen bzw. deren Erfüllbarkeit sicherzustellen
* Anforderungen wie Zuverlässigkeit, Wartbarkeit, Änderbarkeit, Sicherheit, Energieeffizienz zu erreichen
* Verständnis für Strukturen und Konzepte des Systems bei allen relevanten {glossary_url}stakeholder[Stakeholdern] sicherstellen
* Komplexität systematisch zu reduzieren
* architekturrelevante Richtlinien für Implementierung und Betrieb zu spezifizieren

// end::DE[]

// tag::EN[]
[[LG-01-02]]
==== LG 01-02: Understand and Explain the Goals and Benefits of Software Architecture (R1)

Software architects can justify the following essential goals and benefits of software architecture:

* support the design, implementation, maintenance, and operation of systems
* achieve functional requirements or ensure that they can be met
* achieve requirements such as reliability, maintainability, changeability, security, energy efficiency etc.
* ensure that the system's structures and concepts are understood by all relevant {glossary_url}stakeholder[stakeholders]
* systematically reduce complexity
* specify architecturally relevant guidelines for implementation and operation
 
// end::EN[]

// tag::TR[]
[[LG-01-02]]
==== LG 01-02: Yazılım Mimarisinin Hedeflerini ve Faydalarını Anlamak ve Açıklamak (R1)

Yazılım mimarları, yazılım mimarisinin aşağıdaki temel hedeflerini ve faydalarını gerekçelendirebilir:

* sistemlerin tasarımını, uygulamasını, bakımını ve işletimini desteklemek
* fonksiyonel gereksinimleri karşılamak veya karşılanabilir olmalarını sağlamak
* güvenilirlik, bakım yapılabilirlik, değiştirilebilirlik, güvenlik, enerji verimliliği vb. gereksinimleri karşılamak
* sistemin yapı ve kavramlarının tüm ilgili {glossary_url}stakeholder[paydaşlar] tarafından anlaşılmasını sağlamak
* karmaşıklığı sistematik olarak azaltmak
* uygulama ve işletim için mimari açıdan önemli yönergeleri belirlemek

// end::TR[]
