
// tag::DE[]

== Entwurf und Entwicklung von Softwarearchitekturen

|===
| Dauer: 270 Min. | Übungszeit: 90 Min.
|===

=== Zielsetzung
Dieser Abschnitt zielt darauf ab, die Teilnehmenden in die Lage zu versetzen, Architekturentscheidungen so zu treffen, dass Anforderungen der Stakeholder unter Berücksichtigung der Randbedingungen erfüllt werden können.
Sie lernen, Architekturentwürfe zu entwickeln, fundierte Entscheidungen zur Systemzerlegung zu treffen und Abhängigkeiten zwischen Bausteinen zu gestalten.
Zu diesem Zweck lernen sie, grundlegende Ansätze und Heuristiken bei der Architekturentwicklung anzuwenden.
Sie erkennen die Bedeutung von Entwurfsprinzipien und Lösungsmustern und können diese anwenden.
Darüber hinaus werden in diesem Abschnitt der Umgang mit Querschnittsthemen, die Prinzipien des Software-Deployments und die Herausforderungen verteilter Systeme thematisiert.

=== Wesentliche Begriffe

Entwurf; 
Vorgehen beim Entwurf; 
{glossary_url}architectural-decision[Architekturentscheidung]; 
Sichten; 
{glossary_url}interface[Schnittstellen];
technische Konzepte und Querschnittsthemen; 
Architekturmuster; 
Entwurfsmuster; 
Mustersprachen; 
Entwurfsprinzipien; 
Abhängigkeiten;
Kopplung; 
Kohäsion; 
Top-down- und Bottom-up-Vorgehen;
modellbasierter Entwurf; 
iterativer Entwurf; 
Domain-Driven Design

// end::DE[]

// tag::EN[]
== Design and Development of Software Architectures

|===
| Duration: 270 min. | Excercises: 90 min.
|===

=== Purpose
This section aims to enable participants to take architectural decisions in a way that fulfills stakeholder requirements while respecting the given constraints of the system context.
They will learn to develop architectural designs, make informed decisions on system decomposition and shape dependencies between building blocks.
To this end, they learn to apply basic approaches and heuristics in architecture development.
They recognize the importance of design principles and solution patterns and are able to apply them.
In addition, this section addresses the management of cross-cutting concerns, the principles of software deployment and the challenges of distributed systems.

=== Relevant Terms
Design; design approach; {glossary_url}architectural-decision[architecture decision]; views; 
{glossary_url}interface[interfaces];  
technical concepts and
{glossary_url}cross-cutting-concern[cross-cutting concerns];
architectural patterns;
design patterns;
pattern languages; 
design principles; 
dependencies; 
coupling; 
cohesion; 
top-down and bottom-up approaches; 
model-based design; 
iterative design; 
domain-driven design

// end::EN[]

// tag::TR[]
== Yazılım Mimarilerinin Tasarımı ve Geliştirilmesi

|===
| Süre: 270 dk. | Alıştırmalar: 90 dk.
|===

=== Amaç
Bu bölüm; katılımcıların bir yandan sistem bağlamınca tanımlanan sınır koşullarına bağlı kalırken, diğer yandan paydaş gereksinimlerini karşılayacak şekilde mimari kararlar alabilmelerini sağlamayı amaçlar.
Mimari tasarımlar; geliştirmeyi, sistem ayrıştırması hakkında bilinçli kararlar almayı ve yapı taşları arasındaki bağımlılıkları şekillendirmeyi öğreneceklerdir.
Bu amaçla, mimari geliştirmede temel yaklaşımları ve buluşsal yöntemleri uygulamayı öğrenirler.
Tasarım ilkeleri ve çözüm örüntülerinin önemini fark eder ve bunları uygulayabilirler.
Ayrıca, bu bölüm kesişimsel ilgi alanlarının yönetimi, yazılım konuşlandırmasının ilkeleri ve dağıtık sistemlerin zorluklarını ele alır.

=== İlgili Terimler
Tasarım; tasarım yaklaşımı; {glossary_url}architectural-decision[mimari karar]; görünümler;
{glossary_url}interface[arayüzler];
teknik kavramlar ve
{glossary_url}cross-cutting-concern[kesişimsel ilgi alanları];
mimari örüntüler;
tasarım örüntüleri;
örüntü dilleri;
tasarım ilkeleri;
bağımlılıklar;
bağlaşımlar;
bağdaşıklık;
tepeden aşağı ve tabandan yukarı yaklaşımlar;
model tabanlı tasarım;
yinelemeli tasarım;
alan odaklı tasarım

// end::TR[]
