// tag::DE[]

[[LG-03-04]]
==== LZ 03-04 [ehemaliges LZ 2-6]: Entwurfsprinzipien erläutern und anwenden (R1-R3)

Softwarearchitekt:innen sind in der Lage zu erklären, was Entwurfsprinzipien sind.
Sie können deren grundlegende Ziele und deren Anwendung im Hinblick auf Softwarearchitektur skizzieren. (R2)

Softwarearchitekt:innen sind in der Lage:

* die unten aufgeführten Gestaltungsprinzipien zu erläutern und mit Beispielen zu illustrieren
* zu erklären, wie diese Prinzipien angewendet werden sollen
* darzulegen, wie Anforderungen die Anwendung dieser Prinzipien beeinflussen
* die Auswirkungen der Entwurfsprinzipien auf die Implementierung zu erläutern
* Quellcode und Architektur zu analysieren, um zu beurteilen, ob diese Entwurfsprinzipien angewendet wurden oder angewendet werden sollten


**Abstraktion** (R2)

* im Sinne eines Vorgehens zur Erarbeitung zweckmäßiger Generalisierungen
* als eine Entwurfstechnik, bei dem die Bausteine von Abstraktionen und nicht von Implementierungen abhängen
* Schnittstellen als Abstraktionen


**Modularisierung** (R1)

* Geheimnisprinzip ({glossary_url}information-hiding[Information Hiding]) und {glossary_url}encapsulation[Kapselung]
* Trennung von Verantwortlichkeiten ({glossary_url}separation-of-concern[Separation of Concerns] - SoC)
* Lose, aber funktionell ausreichende Kopplung von Bausteinen, siehe <<LG-03-06>>
* Hohe {glossary_url}cohesion[Kohäsion]
* {glossary_url}open-close-principle[Offen/geschlossen-Prinzip]
* {glossary_url}dependency-inversion[Dependency-Inversion-Prinzip] - Umkehrung von Abhängigkeiten durch Schnittstellen oder ähnliche Abstraktionen

**Konzeptionelle Integrität** (R2-R3)

* bedeutet Einheitlichkeit (Homogenität, Konsistenz) von Lösungen für ähnliche Probleme zu erreichen (R2)
* als ein Mittel, um das Prinzip der geringsten Überraschung zu erreichen (_principle of least surprise_ oder _principle of least astonishment_ (POLA)) (R3)
* Liskov’sches Substitutionsprinzip als eine Möglichkeit, Konsistenz, konzeptionelle Integrität und Robustheit (im Sinne von Typsicherheit) zu erreichen (R3).

**Reduktion von Komplexität** (R3)

* als Motiv der Prinzipien KISS, YAGNI und CUPID <<north-cupid>>
* DRY (Don't Repeat Yourself) als eine Möglichkeit, Wiederholungen zu vermeiden 

**Erwarte Fehler** (R2-R3)

* als Mittel für den Entwurf robuster und widerstandsfähiger Systeme (R3)
* als eine Verallgemeinerung des Robustheitsgrundsatzes (_Postel's law_) (R2)

**SOLID Prinzipien** (R3)

Softwarearchitekt:innen kennen Nutzen und Grenzen der SOLID Prinzipien: 
Single Responsibility Principle, Open/Closed Principle, Liskov Substitution Principle, Interface Segregation Principle, Dependency Inversion Principle 

// end::DE[]

// tag::EN[]

[[LG-03-04]]
==== LG 03-04 [previously LG 2-6]: Explain and Use Design Principles (R1-R3)

Software architects are able to explain what design principles are.
They can outline their general objectives and their application with regard to software architecture. (R2)

Software architects are able to:

* explain the design principles listed below and can illustrate them with examples
* explain how those principles are to be applied
* explain how requirements determine which principles should be applied
* explain the impact of design principles on the implementation
* analyze source code and architecture designs to evaluate whether these design principles have been applied or should be applied

**Abstraction** (R2)

* in the sense of a means for deriving useful generalizations
* as a design technique, where building blocks are dependent on the abstractions rather than depending on implementations
* interfaces as abstractions

**Modularization** (R1)

* {glossary_url}information-hiding[information hiding] and {glossary_url}encapsulation[encapsulation]
* {glossary_url}separation-of-concern[separation of concerns] - SoC
* loose, but functionally sufficient, coupling (R1) of building blocks, see <<LG-03-06>>
* high {glossary_url}cohesion[cohesion]
* {glossary_url}open-close-principle[Open/closed principle]
* {glossary_url}dependency-inversion[Dependency inversion principle] by means of interfaces or similar abstractions

**Conceptual integrity** (R2-R3)

* meaning uniformity (homogeneity, consistency) of solutions for similar problems (R2)
* as a means to achieve the principle of least surprise (aka  _principle of least astonishment_, POLA) (R3)
* Liskov's substitution principle as a way to achieve consistency, conceptual integrity and robustness (in the sense of type safety) (R3).

**Complexity reduction** (R3)

* as the driving factor behind KISS, YAGNI, and CUPID <<north-cupid>>
* DRY (Don't Repeat Yourself) as one option to avoid repetitions

**Expect errors** (R2-R3)

* as a means to design for robust and resilient systems (R3)
* as a generalization of the robustness principle (_Postel's law_) (R2)

**SOLID Principles** (R3)

Software architects know the benefits and limitations of the SOLID principles:
Single Responsibility Principle, Open/Closed Principle, Liskov Substitution Principle, Interface Segregation Principle, Dependency Inversion Principle 


// end::EN[]

// tag::TR[]

[[LG-03-04]]
==== LG 03-04 [önceki LG 2-6]: Tasarım İlkelerini Açıklamak ve Kullanmak (R1-R3)

Yazılım mimarları tasarım ilkelerinin ne olduğunu açıklayabilir.
Bunların genel hedeflerini ve yazılım mimarisi açısından uygulamalarını ana hatlarıyla belirtebilirler. (R2)

Yazılım mimarları şunları yapabilir:

* aşağıda listelenen tasarım ilkelerini açıklayabilir ve örneklerle gösterebilir
* bu ilkelerin nasıl uygulanacağını açıklayabilir
* hangi ilkelerin uygulanması gerektiğini gereksinimlerin nasıl belirlediğini açıklayabilir
* tasarım ilkelerinin uygulama üzerindeki etkisini açıklayabilir
* bu tasarım ilkelerinin uygulanıp uygulanmadığını veya uygulanması gerekip gerekmediğini değerlendirmek için kaynak kodu ve mimari tasarımları analiz edebilir

**Soyutlama** (R2)

* yararlı genellemeler türetmenin bir aracı anlamında
* yapı taşlarının uygulamalara değil soyutlamalara bağlı olduğu bir tasarım tekniği olarak
* soyutlamalar olarak arayüzler

**Modülerleştirme** (R1)

* {glossary_url}information-hiding[Bilgi Gizleme] ve {glossary_url}encapsulation[Sarma]
* {glossary_url}separation-of-concern[Sorumlulukların Ayrılması] - SoC
* yapı taşlarının gevşek, ancak işlevsel olarak yeterli bağlaşımı (R1), bkz. <<LG-03-06>>
* yüksek {glossary_url}cohesion[bağdaşıklık]
* {glossary_url}open-close-principle[Açıklık-Kapalılık İlkesi]
* arayüzler veya benzeri soyutlamalar aracılığıyla {glossary_url}dependency-inversion[Bağımlılık Evirimi İlkesi]

**Kavramsal bütünlük** (R2-R3)

* benzer problemler için çözümlerin tekdüzeliği (homojenlik, tutarlılık) anlamında (R2)
* en az sürpriz ilkesine (diğer adıyla _en az şaşkınlık ilkesi_, POLA) ulaşmanın bir aracı olarak (R3)
* tutarlılık, kavramsal bütünlük ve sağlamlığa (tür güvenliği anlamında) ulaşmanın bir yolu olarak Liskov ikame ilkesi (R3).

**Karmaşıklık azaltma** (R3)

* KISS, YAGNI ve CUPID'in ardındaki itici faktör olarak <<north-cupid>>
* tekrarlardan kaçınmanın bir seçeneği olarak DRY (Don't Repeat Yourself)

**Hataları bekle** (R2-R3)

* sağlam ve dayanıklı sistemler tasarlamanın bir aracı olarak (R3)
* sağlamlık ilkesinin (_Postel yasası_) bir genellemesi olarak (R2)

**SOLID İlkeleri** (R3)

Yazılım mimarları SOLID ilkelerinin faydalarını ve sınırlamalarını bilir:
Tek Sorumluluk İlkesi, Açıklık-Kapalılık İlkesi, Liskov İkame İlkesi, Arayüz Ayrım İlkesi, Bağımlılık Evirimi İlkesi


// end::TR[]

===== {references}
<<liskov>>, <<solid>>
