// tag::DE[]

[[LG-03-06]]
==== LZ 03-06 [ehemaliges LZ 2-7]: Abhängigkeiten von Bausteinen managen (R1)

Softwarearchitekt:innen verstehen Abhängigkeiten und Kopplung zwischen Bausteinen und können diese gezielt einsetzen.
Sie:

* kennen und verstehen unterschiedliche Arten der Kopplung von Bausteinen (beispielsweise  Kopplung über Benutzung/Delegation, Nachrichten/Ereignisse, Komposition, Erzeugung, Vererbung, zeitliche Kopplung, Kopplung über Daten, Datentypen oder Hardware)
* verstehen, wie Abhängigkeiten die Kopplung vergrößern
* können mindestens die folgenden Arten von Kopplung unterscheiden:
** statische und dynamische Kopplung 
** efferente und afferente Kopplung 
* wissen, dass auf statische Kopplung zu verzichten und stattdessen dynamische Kopplung einzusetzen, die zugrundeliegende Kopplung nicht notwendigerweise reduziert
* können Kopplung erkennen und ihre Auswirkungen bewerten
* können begründete Entscheidungen treffen, ob eine Abhängigkeit in Anbetracht der Anforderungen und Randbedingungen angemessen ist oder entfernt werden sollte
* kennen Möglichkeiten zur Auflösung bzw. Reduktion von Kopplung und können diese anwenden, beispielsweise:
** Muster
// (siehe <<LZ-2-5, LZ 2-5>>)
** Grundlegende Entwurfsprinzipien
// (siehe <<LZ-2-6, LZ 2-6>>)
** Externalisierung von Abhängigkeiten, d.h. konkrete Abhängigkeiten erst zur Installations- oder Laufzeit festlegen, etwa durch Anwendung von
{glossary_url}dependency-injection[Dependency Injection] (R3) (siehe auch <<LG-03-08>>).


// end::DE[]

// tag::EN[]
[[LG-03-06]]
==== LG 03-06 [previously LG 2-7]: Manage Dependencies between Building Blocks (R1)

Software architects understand dependencies and coupling between building blocks and can use them in a targeted manner. They:

* know and understand different types of dependencies of building blocks (e.g. coupling via use/delegation, messaging/events, composition, creation, inheritance, temporal coupling, coupling via data, data types or hardware)
* understand how dependencies increase coupling
* can differentiate between at least the following categories of coupling:
** static and dynamic coupling 
** efferent and afferent coupling 
* know that forgoing static dependencies in favor of dynamic dependencies does not necessarily reduce the underlying coupling
* can identify coupling and assess its consequences
* can make justified decisions whether a dependency is appropriate or should be removed in view of the requirements and constraints
* know and can apply possibilities to reduce or eliminate coupling, for example:
** patterns
// (refer to <<LG-2-5, LG 2-5>>)
** fundamental design principles
// (refer to <<LG-2-6, LG 2-6>>)
** externalization of dependencies, i.e. defining concrete dependencies at installation- or runtime, for example by using
{glossary_url}dependency-injection[Dependency Injection] (R3) (see also <<LG-03-08>>).

// end::EN[]

// tag::TR[]
[[LG-03-06]]
==== LG 03-06 [önceki LG 2-7]: Yapı Taşları Arasındaki Bağımlılıkları Yönetmek (R1)

Yazılım mimarları, yapı taşları arasındaki bağımlılıkları ve bağlaşımı anlar ve bunları hedefli bir şekilde kullanabilir. Onlar:

* yapı taşlarının farklı bağımlılık türlerini bilir ve anlar (örneğin kullanım/delegasyon, mesajlaşma/olaylar, kompozisyon, oluşturma, kalıtım, zamansal bağlılık, veri, veri tipleri veya donanım üzerinden bağlaşımlar)
* bağımlılıkların bağlaşımı nasıl artırdığını anlar
* en azından aşağıdaki bağlaşım kategorilerini ayırt edebilir:
** statik ve dinamik bağlaşım
** efferent ve afferent bağlaşım
* dinamik bağımlılıklar lehine statik bağımlılıklardan vazgeçmenin altta yatan bağlaşımı mutlaka azaltmadığını bilir
* bağlaşımı belirleyebilir ve sonuçlarını değerlendirebilir
* bir bağımlılığın gereksinimler ve sınır koşulları göz önünde bulundurulduğunda uygun olup olmadığı veya kaldırılması gerekip gerekmediği hakkında gerekçeli kararlar verebilir
* bağlaşımı azaltma veya ortadan kaldırma olanaklarını bilir ve uygulayabilir, örneğin:
** örüntüler
** temel tasarım ilkeleri
** bağımlılıkların dışsallaştırılması, yani somut bağımlılıkların kurulum veya yürütüm zamanında tanımlanması, örneğin
{glossary_url}dependency-injection[BAğımlılık Enjeksiyonu] kullanarak (R3) (ayrıca bkz. <<LG-03-08>>).

// end::TR[]

===== {references}
<<fordhardparts>>
