
// tag::DE[]
[[LG-03-10]]
==== LZ 03-10 [ehemaliges LZ 2-4]: Querschnittsthemen identifizieren und Querschnittskonzepte entwerfen und umsetzen (R1)

Softwarearchitekt:innen können:

* die Bedeutung von {glossary_url}cross-cutting-concern[Querschnittsthemen] erklären
* solche Querschnittsthemen identifizieren
* Querschnittskonzepte entwerfen, unter anderem Persistenz, Kommunikation, GUI, Fehlerbehandlung, Nebenläufigkeit, Energieeffizienz
* mögliche wechselseitige Abhängigkeiten erkennen und beurteilen.

Softwarearchitekt:innen wissen, dass solche Querschnittskonzepte systemübergreifend wiederverwendbar sein können.

Siehe auch <<LG-04-07>>.
// end::DE[]

// tag::EN[]
[[LG-03-10]]
==== LG 03-10 [previously LG 2-4]: Identify, Design and Implement Cross-Cutting Concerns (R1)

Software architects are able to:

* explain the significance of {glossary_url}cross-cutting-concern[cross-cutting concerns]
* identify cross-cutting concerns
* design cross-cutting concepts, for example persistence, communication, GUI, error handling, concurrency, energy efficiency
* identify and assess potential interdependencies.

Software architects know that such cross-cutting concepts may be re-used across systems.

See also <<LG-04-07>>.

// end::EN[]

// tag::TR[]
[[LG-03-10]]
==== LG 03-10 [önceki LG 2-4]: Kesişen İlgi Alanlarını Belirlemek, Tasarlamak ve Uygulamak (R1)

Yazılım mimarları şunları yapabilir:

* {glossary_url}cross-cutting-concern[kesişen ilgi alanlarının] önemini açıklamak
* kesişen ilgi alanlarını belirlemek
* kesişen kavramları tasarlamak, örneğin kalıcılık, iletişim, GUI, hata işleme, eşzamanlılık, enerji verimliliği
* olası karşılıklı bağımlılıkları belirlemek ve değerlendirmek.

Yazılım mimarları, bu tür kesişen kavramların sistemler arasında yeniden kullanılabileceğini bilir.

Ayrıca bkz. <<LG-04-07>>.

// end::TR[]

===== {references}
<<starke>>, <<starkelorz>>
