
// tag::DE[]
[[LG-02-04]]
==== LZ 02-04 [ehemaliges LZ 4-2]: Anforderungen an Qualitäten formulieren (R1-R3)

Softwarearchitekt:innen:

* können Szenarien für gegebene Qualitäten mit Kontext, Stimulus, Reaktion und Messung für verschiedene Zwecke formulieren, z. B. um Anforderungen zu klären, Input für Architekturbewertungen zu liefern usw. (R1)

* verstehen, dass eine Anforderung für eine gegebene Qualität
  eine Analysemethode spezifizieren sollte (siehe <<LG-05-02>>) (R1)
* wissen, dass die Verwendung einer Metrik als Ziel diese invalidieren kann (R2), wie z.{nbsp}B. in Goodhart's Law (R3) beschrieben

// end::DE[]

// tag::EN[]
[[LG-02-04]]
==== LG 02-04 [previously LG 4-2]: Formulate Requirements on Qualities (R1-R3)

Software architects:

* can formulate scenarios for given qualities with context, stimulus, response, and measurement for a variety of purposes, e.g., to clarify requirements, provide input for architecture assessments, etc. (R1)
* understand that a requirement for a given quality should specify a method of analysis (see <<LG-05-02>>) (R1)
* know that the use of a metric as a target can lead to its  invalidation (R2), as described, e.g., by Goodhart's law (R3)

// end::EN[]

// tag::TR[]
[[LG-02-04]]
==== LG 02-04 [önceki LG 4-2]: Kalitelere İlişkin Gereksinimleri Formüle Etmek (R1-R3)

Yazılım mimarları:

* gereksinimleri netleştirmek, mimari değerlendirmeler için girdi sağlamak vb. gibi çeşitli amaçlar için bağlam, uyaran, yanıt ve ölçüm içeren verilen kaliteler için senaryolar formüle edebilir (R1)
* belirli bir kalite için bir gereksinimin bir analiz yöntemi belirtmesi gerektiğini anlar (bkz. <<LG-05-02>>) (R1)
* bir metriğin hedef olarak kullanılmasının geçersiz kılınmasına yol açabileceğini bilir (R2), örneğin Goodhart yasasında açıklandığı gibi (R3)

// end::TR[]

===== {references}
<<bass>>, <<q42>>, <<iso25010>>
