
// tag::DE[]
== Analyse und Bewertung von Softwarearchitekturen

|===
| Dauer: 60 Min. | Übungszeit: 30 Min.
|===

=== Zielsetzung
In diesem Abschnitt sollen Softwarearchitekt:innen die Fähigkeiten und Kenntnisse vermittelt werden, die sie für eine effektive Architekturanalyse benötigen.
Sie lernen, Risiken zu erkennen, die Konformität mit Architekturentscheidungen zu bewerten und die Gesamtqualität eines Systems auf der Grundlage seines Designs und seiner Implementierung zu beurteilen.
Durch das Verständnis verschiedener Analysemethoden wie Abnahmetests, Architekturmetriken, szenariobasierte Analyse und Kosten-Nutzen-Analysen können Architekt:innen sicherstellen, dass eine Softwarearchitektur den Anforderungen der Stakeholder entspricht und mit dem beabsichtigten Design übereinstimmt.


===	Wesentliche Begriffe

Architekturanalyse; Risikoidentifikation; Qualitätsanalysemethoden; Szenarien; szenariobasierte Analyse; Metriken; Tool-gestützte Analyse


// end::DE[]

// tag::EN[]
== Analysis and Assessment of Software Architectures

|===
| Duration: 60 min. | Exercises: 30 min.
|===

=== Purpose
The purpose of this section is to equip software architects with the skills and knowledge needed to effectively perform architecture analysis.
They learn to identify risks, evaluate conformance to architectural decisions, and assess the overall quality of a system based on its design and implementation.
By understanding various analysis methods, such as acceptance testing, architecture metrics, scenario-based analysis, and cost-benefit analysis, architects can ensure that a software architecture meets stakeholder requirements and is aligned with the intended design.

=== Relevant Terms

Architecture analysis; Risk identification; Quality analysis methods; Scenarios; Scenario-based analysis; Metrics; Tool-supported analysis
// end::EN[]

// tag::TR[]
== Yazılım Mimarilerinin Analizi ve Değerlendirmesi

|===
| Süre: 60 dk. | Alıştırmalar: 30 dk.
|===

=== Amaç
Bu bölümün amacı, yazılım mimarlarını mimari analizi etkili bir şekilde gerçekleştirmek için gereken beceri ve bilgilerle donatmaktır.
Riskleri belirlemeyi, mimari kararlara uygunluğu değerlendirmeyi ve bir sistemin genel kalitesini tasarım ve uygulamasına göre değerlendirmeyi öğrenirler.
Kabul testi, mimari metrikler, senaryo tabanlı analiz ve maliyet-fayda analizi gibi çeşitli analiz yöntemlerini anlayarak, mimarlar yazılım mimarisinin paydaş gereksinimlerini karşıladığından ve amaçlanan tasarımla uyumlu olduğundan emin olabilir.

=== İlgili Terimler

Mimari analizi; Risk belirleme; Kalite analizi yöntemleri; Senaryolar; Senaryo tabanlı analiz; Metrikler; Araç destekli analiz
// end::TR[]
