
<<<
// tag::DE[]
=== Abgrenzung
Dieser Lehrplan reflektiert den aus heutiger Sicht des iSAQB e.V. notwendigen und sinnvollen Inhalt zur Erreichung der Lernziele des CPSA-F. Er stellt keine vollständige Beschreibung des Wissensgebiets „Softwarearchitektur“ dar.

Folgende Themen oder Konzepte sind *nicht Bestandteil des CPSA-F*:

* konkrete Implementierungstechnologien, -frameworks oder -bibliotheken
* Programmierung oder Programmiersprachen
* Spezifische Vorgehensmodelle
* Grundlagen oder Notationen der Modellierung (wie etwa UML)
* Systemanalyse und Requirements Engineering (siehe dazu das Ausbildungs- und Zertifizierungsprogramm des IREB e. V., https://ireb.org, International Requirements Engineering Board)
* Test (siehe dazu das Ausbildungs- und Zertifizierungsprogramm des ISTQB e. V., https://istqb.org, International Software Testing Qualification Board)
* Projekt- oder Produktmanagement
* Einführung in spezifische Werkzeuge.

Ziel des Trainings ist es, die Grundlagen für den Erwerb der für den jeweiligen Einsatzfall notwendigen weiterführenden Kenntnisse und Fertigkeiten zu vermitteln.

// end::DE[]

// tag::EN[]
=== Out of Scope
This curriculum reflects the contents currently considered by the iSAQB members to be necessary and useful for achieving the learning goals of CPSA-F. It is not a comprehensive description of the entire domain of 'software architecture'.

The following topics or concepts are not part of CPSA-F:

* specific implementation technologies, frameworks or libraries
* programming or programming languages
* specific process models
* fundamentals of modelling notations (such as UML) or fundamentals of modelling itself
* system analysis and requirements engineering (please refer to the education and certification program by IREB e. V., https://ireb.org, International Requirements Engineering Board)
* software testing (please refer to the education and certification program by ISTQB e.V., https://istqb.org, International Software Testing Qualification Board)
* project or product management
* introduction to specific software tools.

The aim of the training is to provide the basics for acquiring the advanced knowledge and skills required for the respective application.

// end::EN[]

// tag::TR[]
=== Kapsam Dışı
Bu müfredat, iSAQB üyeleri tarafından şu anda CPSA-F'nin öğrenme hedeflerine ulaşmak için gerekli ve yararlı olduğu düşünülen içerikleri yansıtmaktadır. "Yazılım mimarisi" alanının tamamının kapsamlı bir tanımı değildir.

Aşağıdaki konular veya kavramlar CPSA-F kapsamında *değildir*:

* belirli uygulama teknolojileri, çerçeveler veya kütüphaneler
* programlama veya programlama dilleri
* belirli süreç modelleri
* modelleme gösterimlerinin (UML gibi) temelleri veya modellemenin kendisinin temelleri
* sistem analizi ve gereksinim mühendisliği (IREB e. V. tarafından sunulan eğitim ve sertifikasyon programına bakınız, https://ireb.org, International Requirements Engineering Board)
* yazılım testi (ISTQB e.V. tarafından sunulan eğitim ve sertifikasyon programına bakınız, https://istqb.org, International Software Testing Qualification Board)
* proje veya ürün yönetimi
* belirli yazılım araçlarına giriş.

Eğitimin amacı, ilgili uygulama için gerekli olan ileri düzey bilgi ve becerilerin edinilmesi için temel bilgileri sağlamaktır.

// end::TR[]

