
// tag::DE[]
=== Voraussetzungen

====
Der iSAQB e. V. kann in Zertifizierungsprüfungen die hier genannten Voraussetzungen durch entsprechende Fragen prüfen.
====

Teilnehmende sollten die im Nachfolgenden genannten Kenntnisse und/oder Erfahrung mitbringen. Insbesondere bilden substanzielle praktischen Erfahrungen aus der Softwareentwicklung im Team eine wichtige Voraussetzung zum Verständnis des vermittelten Lernstoffes und für eine erfolgreiche Zertifizierung.

* mehr als 18 Monate praktische Erfahrung in arbeitsteiliger Softwareentwicklung (d.h. in Teams), erworben durch Programmierung unterschiedlicher Systeme außerhalb der Ausbildung
* Kenntnisse und praktische Erfahrung in mindestens einer höheren Programmiersprache, insbesondere:
** Konzepte der 
*** Modularisierung (Pakete, Namensräume)
*** Parameterübergabe (_Call-by-Value, Call-by-Reference_)
*** Gültigkeit (_scope_), beispielsweise von Typ- oder Variablendeklaration und -definition
** Grundlagen von Typsystemen (statische und dynamische Typisierung, generische Datentypen)
** Fehler- und Ausnahmebehandlung in Software
** Mögliche Probleme von globalem Zustand und globalen Variablen

* Grundlegende Kenntnisse von:
** Modellierung und Abstraktion
** Algorithmen und Datenstrukturen (etwa Listen, Bäume, HashTable, Dictionary/Map)
** UML (Klassen-, Paket-, Komponenten- und Sequenzdiagramme) und deren Bezug zum Quellcode
 ** Vorgehen beim Testen von Software (z.{nbsp}B. Unit- und Akzeptanztests)


Hilfreich für das Verständnis einiger Konzepte sind darüber hinaus:

* Grundbegriffe bzw. Unterschiede von imperativer, deklarativer, objektorientierter und funktionaler Programmierung
* praktische Erfahrung in 
** einer höheren Programmiersprache
** Konzeption und Implementierung verteilt ablaufender Anwendungen, wie etwa Client/Server-Systeme oder Web-Anwendungen
** technischer Dokumentation, insbesondere in der Dokumentation von Quellcode, Systementwürfen oder technischen Konzepten

// end::DE[]


// tag::EN[]
=== Prerequisites

====
The iSAQB e. V. may check the following prerequisites in certification examinations via corresponding questions.
====

Participants should have the following knowledge and/or experience. 
In particular, substantial practical experience from software development in a team is an important prerequisite for understanding the learning material and successful certification.

* more than 18 months of practical experience with software development, gained through team-based development of several systems outside of formal education
* knowledge of and practical experience with at least one higher programming language, especially:
** concepts of 
*** modularization (packages, namespaces, etc.)
*** parameter-passing (_call-by-value, call-by-reference_)
*** _scope_, i.e. of type and variable declaration and definition
** basics of type systems (static vs. dynamic typing, generic data types)
** error and exception handling in software
** potential problems of global state and global variables

* Basic knowledge of:
** modelling and abstraction
** algorithms and data structures (i.e. Lists, Trees, HashTable, Dictionary, Map)
** UML (class, package, component and sequence diagrams) and their relation to source code
** approaches to testing of software (e.g. unit- and acceptance testing)


Furthermore, the following will be useful for understanding several concepts:

* basics and differences of imperative, declarative, object-oriented and functional programming
* practical experience in 
** a higher level programming language
** designing and implementing distributed applications, such as client-server systems or web applications
** technical documentation, especially documenting source code, system design or technical concepts

// end::EN[]

// tag::TR[]
=== Ön Koşullar

====
iSAQB e. V., sertifikasyon sınavlarında aşağıdaki ön koşulları ilgili sorularla kontrol edebilir.
====

Katılımcılar aşağıdaki bilgi ve/veya deneyime sahip olmalıdır.
Özellikle, bir ekipte yazılım geliştirme konusunda önemli pratik deneyim, öğrenme materyalini anlamak ve başarılı sertifikasyon için önemli bir ön koşuldur.

* örgün eğitim dışında birden fazla sistemin ekip tabanlı geliştirilmesi yoluyla kazanılmış, yazılım geliştirme alanında 18 aydan fazla pratik deneyim
* en az bir üst düzey programlama dilinde bilgi ve pratik deneyim, özellikle:
** aşağıdaki kavramlar:
*** modülerleştirme (paketler, isim alanları vb.)
*** parametre geçişi (_değer ile çağrı, referans ile çağrı_)
*** _kapsam_, yani tür ve değişken bildirimi ve tanımı
** tür sistemlerinin temelleri (statik ve dinamik türleme, jenerik veri türleri)
** yazılımda hata ve istisna işleme
** global durum ve global değişkenlerin potansiyel sorunları

* Temel bilgiler:
** modelleme ve soyutlama
** algoritmalar ve veri yapıları (Listeler, Ağaçlar, HashTable, Dictionary, Map gibi)
** UML (sınıf, paket, bileşen ve sıra diyagramları) ve bunların kaynak kodla ilişkisi
** yazılım test yaklaşımları (örneğin birim ve kabul testleri)


Ayrıca, bazı kavramların anlaşılması için aşağıdakiler faydalı olacaktır:

* imperatif, deklaratif, nesne yönelimli ve fonksiyonel programlamanın temelleri ve farkları
* aşağıdaki alanlarda pratik deneyim:
** üst düzey bir programlama dili
** istemci-sunucu sistemleri veya web uygulamaları gibi dağıtık uygulamaların tasarımı ve uygulanması
** teknik dokümantasyon, özellikle kaynak kodu, sistem tasarımı veya teknik kavramların belgelenmesi

// end::TR[]


