// tag::DE[]
[[LG-06-02]]
==== LZ 06-02  [ehemaliges LZ 5-2]: Technische Umsetzung einer Lösung nachvollziehen (R3)

Softwarearchitekt:innen können anhand mindestens eines Beispiels die technische Umsetzung (Implementierung, technische Konzepte, eingesetzte Produkte, Lösungsstrategien) einer Lösung nachvollziehen.

// end::DE[]

// tag::EN[]
[[LG-06-02]]
==== LG 06-02  [previous LG 5-2]: Understand the technical implementation of a solution (R3)

Software architects understand the technical realization (implementation, technical concepts, products used, architectural decisions, solution strategies) of at least one solution.

// end::EN[]

// tag::TR[]
[[LG-06-02]]
==== LG 06-02 [önceki LG 5-2]: Bir Çözümün Teknik Uygulamasını Anlamak (R3)

Yazılım mimarları en az bir çözümün teknik gerçekleştirmesini (uygulama, teknik kavramlar, kullanılan ürünler, mimari kararlar, çözüm stratejileri) anlar.

// end::TR[]

===== {references}
<<arc42>>, <<starkeetalarc42>>, <<hruschkaetalarc42>>, <<zoerner>>, <<aosa>>