// tag::DE[]
[[LG-04-05]]
==== LZ 04-05 [ehemaliges LZ 3-4]: Architektursichten erläutern und anwenden (R1)
Softwarearchitekt:innen können folgende Architektursichten anwenden:

* Kontextsicht (auch genannt Kontextabgrenzung)
  ** enthält die externen Schnittstellen von Systemen
  ** bei Bedarf differenziert nach fachlichem und technischem Kontext

* Baustein- oder Komponentensicht (Aufbau des Systems aus Softwarebausteinen)
* Laufzeitsicht (dynamische Sicht, Zusammenwirken der Softwarebausteine zur Laufzeit, Zustandsmodelle)
* Verteilungs-/Deploymentsicht (Hardware und technische Infrastruktur sowie Abbildung von Softwarebausteinen auf diese Infrastruktur)

Zusätzliche Sichten können nach Bedarf verwendet werden, um weitere Anliegen oder Anforderungen von Stakeholden zu berücksichtigen, z. B. Funktionale Sicherheit, Informations-, Betriebs- oder User-Interface Sicht (R3).
// end::DE[]

// tag::EN[]
[[LG-04-05]]
==== LG 04-05 [previously LG 3-4]: Explain and Use Architectural Views (R1)
Software architects are able to use the following architectural views:

* context view
  ** contains the external interfaces of systems 
  ** when appropriate differentiated according to business and technical context

* building block or component view (composition of software building blocks)
* runtime view (dynamic view, interaction between software building blocks at runtime, state machines)
* deployment view (hardware and technical infrastructure as well as the mapping of software building blocks onto the infrastructure)

Additional views might be used as needed to address further stakeholder concerns and requirements, such as functional safety, information view,  operational view or user-interface view (R3).
// end::EN[]

// tag::TR[]
[[LG-04-05]]
==== LG 04-05 [önceki LG 3-4]: Mimari Görünümleri Açıklamak ve Kullanmak (R1)
Yazılım mimarları aşağıdaki mimari görünümleri kullanabilir:

* bağlam görünümü
  ** sistemlerin dış arayüzlerini içerir
  ** uygun olduğunda iş ve teknik bağlama göre farklılaştırılır

* yapı taşı veya bileşen görünümü (yazılım yapı taşlarının bileşimi)
* çalışma zamanı görünümü (dinamik görünüm, çalışma zamanında yazılım yapı taşları arasındaki etkileşim, durum makineleri)
* dağıtım görünümü (donanım ve teknik altyapı ile yazılım yapı taşlarının altyapıya eşlenmesi)

Ek görünümler, fonksiyonel güvenlik, bilgi görünümü, operasyonel görünüm veya kullanıcı arayüzü görünümü gibi diğer paydaş ilgi alanlarını ve gereksinimlerini ele almak için gerektiğinde kullanılabilir (R3).
// end::TR[]

===== {references}
<<kruchten95>>, <<rozanskiwoods>>, <<starkelorz>>, <<arc42>>, <<brownc4>>


