
// tag::DE[]
[[LG-04-08]]
==== LZ 04-08 [ehemaliges LZ 3-8]: Architekturentscheidungen erläutern und dokumentieren (R1-R2)

Softwarearchitekt:innen können:

* Architekturentscheidungen systematisch herbeiführen, begründen, kommunizieren und dokumentieren
* gegenseitige Abhängigkeiten solcher Entscheidungen erkennen, kommunizieren und dokumentieren

Softwarearchitekt:innen kennen Architecture-Decision-Records (ADR, siehe <<nygard>>) und können diese zur Dokumentation von Entscheidungen einsetzen (R2).
// end::DE[]

// tag::EN[]
[[LG-04-08]]
==== LG 04-08 [previously LG 3-8]: Explain and Document Architectural Decisions (R1-R2)

Software architects are able to:

* systematically make, justify, communicate, and document architectural decisions
* identify, communicate, and document interdependencies between architecture decisions

Software architects know about Architecture-Decision-Records (ADR, see <<nygard>>) and can apply these to document decisions (R2).

// end::EN[]

// tag::TR[]
[[LG-04-08]]
==== LG 04-08 [önceki LG 3-8]: Mimari Kararları Açıklamak ve Dokümante Etmek (R1-R2)

Yazılım mimarları şunları yapabilir:

* mimari kararları sistematik olarak almak, gerekçelendirmek, iletmek ve dokümante etmek
* mimari kararlar arasındaki karşılıklı bağımlılıkları belirlemek, iletmek ve dokümante etmek

Yazılım mimarları Mimari Karar Kayıtlarını (ADR, bkz. <<nygard>>) bilir ve kararları dokümante etmek için bunları uygulayabilir (R2).

// end::TR[]

===== {references}
<<nygard>>