// tag::DE[]
[[LG-04-02]]
==== LZ 04-02 [ehemaliges LZ 3-2]: Softwarearchitekturen beschreiben und kommunizieren (R1-R3)

Softwarearchitekt:innen nutzen Dokumentation zur Unterstützung bei Entwurf, Implementierung und Weiterentwicklung (auch genannt _Wartung_ oder _Evolution_) von Systemen. (R2)

Softwarearchitekt:innen (R1):

* können Architekturen entsprechend der Anliegen der Stakeholder dokumentieren und kommunizieren und dadurch unterschiedliche Zielgruppen adressieren, z.{nbsp}B. Management, Entwicklungsteams, QS, andere Softwarearchitekt:innen sowie möglicherweise zusätzliche Stakeholder
* können die Beiträge unterschiedlicher Autorengruppen stilistisch und inhaltlich konsolidieren und harmonisieren
* können Maßnahmen entwickeln und umsetzen, die mündliche und schriftliche Kommunikation in Einklang miteinander halten und miteinander angemessen ausbalancieren
* kennen den Nutzen von Template-basierter Dokumentation
* wissen, dass verschiedene Eigenschaften der Dokumentation von Spezifika des Systems, seinen Anforderungen, Risiken, dem Entwicklungsvorgehen, der Organisation oder anderen Faktoren abhängen.

Sie können beispielsweise die folgenden Merkmale von Dokumentation je nach Situation anpassen (R3):

* Umfang und Detaillierungsgrad der benötigten Dokumentation
* das Dokumentationsformat
* die Zugänglichkeit der Dokumentation
* Formalitäten der Dokumentation (z.{nbsp}B. Diagramme, die einem Metamodell entsprechen, oder einfache Zeichnungen)
* formale Überprüfungen und Freigabeprozesse für die Dokumentation


// end::DE[]

// tag::EN[]
[[LG-04-02]]
==== LG 04-02 [previously LG 3-2]: Describe and Communicate Software Architectures (R1-R3)

Software architects use documentation to support the design, implementation and further development (also called _maintenance_ or _evolution_) of systems (R2)

Software architects are able to (R1):

* document and communicate architectures for corresponding stakeholder concerns, thereby addressing different target groups, e.g. management, development teams, QA, other software architects, and possibly additional stakeholders
* consolidate and harmonise the style and content of contributions from different groups of authors
* develop and implement measures to support the consistency of written and verbal communication, and balance one against the other appropriately

Software architects know (R1):

* the benefits of template-based documentation
* that various properties of documentation depend on specific properties of the system, its requirements, risks, development process, organization or other factors.

For example, software architects can adjust the following documentation characteristics according to the situation (R3):

* the amount and level of detail of documentation needed
* the documentation format
* the accessibility of the documentation
* formality of documentation (e.g. diagrams compliant to a meta model or simple drawings)
* formal reviews and sign-off processes for documentation


// end::EN[]

// tag::TR[]
[[LG-04-02]]
==== LG 04-02 [önceki LG 3-2]: Yazılım Mimarilerini Tanımlamak ve İletmek (R1-R3)

Yazılım mimarları, sistemlerin tasarımını, uygulanmasını ve daha fazla geliştirilmesini (_bakım_ veya _evrim_ olarak da adlandırılır) desteklemek için dokümantasyonu kullanır (R2)

Yazılım mimarları şunları yapabilir (R1):

* ilgili paydaş ilgi alanları için mimarileri dokümante etmek ve iletmek, böylece farklı hedef kitlelere hitap etmek, örn. yönetim, geliştirme ekipleri, kalite güvence, diğer yazılım mimarları ve muhtemelen ek paydaşlar
* farklı yazar gruplarından gelen katkıların stilini ve içeriğini birleştirmek ve uyumlaştırmak
* yazılı ve sözlü iletişimin tutarlılığını desteklemek ve birini diğerine karşı uygun şekilde dengelemek için önlemler geliştirmek ve uygulamak

Yazılım mimarları şunları bilir (R1):

* şablon tabanlı dokümantasyonun faydaları
* dokümantasyonun çeşitli özelliklerinin sistemin belirli özelliklerine, gereksinimlerine, risklerine, geliştirme sürecine, organizasyona veya diğer faktörlere bağlı olduğu.

Örneğin, yazılım mimarları aşağıdaki dokümantasyon özelliklerini duruma göre ayarlayabilir (R3):

* ihtiyaç duyulan dokümantasyonun miktarı ve ayrıntı düzeyi
* dokümantasyon formatı
* dokümantasyonun erişilebilirliği
* dokümantasyonun biçimselliği (örn. meta modele uyumlu diyagramlar veya basit çizimler)
* dokümantasyon için resmi incelemeler ve onay süreçleri


// end::TR[]
