
// tag::DE[]
[[LG-04-03]]
==== LZ 04-03 [ehemaliges LZ 3-3]: Notations-/Modellierungsmittel für Beschreibung von Softwarearchitektur erläutern und anwenden (R2-R3)

Softwarearchitekt:innen kennen mindestens folgende UML-Diagramme zur Notation von Architektursichten:

* Klassen-, Paket-, Komponenten- (jeweils R2) und Kompositionsstrukturdiagramme (R3)
* Verteilungsdiagramme (R2)
* Sequenz- und Aktivitätsdiagramme (R2)
* Zustandsdiagramme (R3)

Softwarearchitekt:innen kennen Alternativen zu UML, beispielsweise (R3)

* ArchiMate
* SysML
* C4, siehe <<brownc4>>
* Entity-Relationship Diagramme, siehe <<erd>>
* für Laufzeitsichten beispielsweise Flussdiagramme, nummerierte Listen oder Business-Process-Modelling-Notation (BPMN).

// end::DE[]

// tag::EN[]
[[LG-04-03]]
==== LG 04-03 [previously LG 3-3]: Explain and Apply Notations/Models to Describe Software Architecture (R2-R3)

Software architects know at least the following UML diagrams to describe architectural views:

* class, package, component (all R2) and composite-structure diagrams (R3)
* deployment diagrams (R2)
* sequence and activity diagrams (R2)
* state machine diagrams (R3)

Software architects know alternative notations to UML diagrams, for example: (R3)

* Archimate
* SysML
* C4, see <<brownc4>>
* Entity-relationship diagrams, see <<erd>>
* for runtime views for example flow charts, numbered lists or business-process-modeling-notation (BPMN).

// end::EN[]

// tag::TR[]
[[LG-04-03]]
==== LG 04-03 [önceki LG 3-3]: Yazılım Mimarisini Tanımlamak İçin Gösterimleri/Modelleri Açıklamak ve Uygulamak (R2-R3)

Yazılım mimarları mimari görünümleri tanımlamak için en azından aşağıdaki UML diyagramlarını bilir:

* sınıf, paket, bileşen (tümü R2) ve bileşik yapı diyagramları (R3)
* dağıtım diyagramları (R2)
* sıra ve etkinlik diyagramları (R2)
* durum makinesi diyagramları (R3)

Yazılım mimarları UML diyagramlarına alternatif gösterimleri bilir, örneğin: (R3)

* Archimate
* SysML
* C4, bkz. <<brownc4>>
* Varlık-ilişki diyagramları, bkz. <<erd>>
* çalışma zamanı görünümleri için örneğin akış şemaları, numaralı listeler veya iş süreci modelleme notasyonu (BPMN).

// end::TR[]

===== {references}
<<uml>>, <<archimate>>, <<sysml>>, <<brownc4>>, <<erd>>