
// tag::DE[]
[[LG-04-09]]
==== LZ 04-09 [ehemaliges LZ 3-9]: Weitere Hilfsmittel und Werkzeuge zur Dokumentation kennen (R3)

Softwarearchitekt:innen kennen:

* Grundlagen mehrerer publizierter Frameworks zur Beschreibung von Softwarearchitekturen, beispielsweise:
** ISO/IEC/IEEE 42010, 
** arc42,
** C4, siehe <<brownc4>>
* Ideen und Beispiele von Checklisten für die Erstellung, Dokumentation und Prüfung von Softwarearchitekturen
* mögliche Werkzeuge zur Erstellung und Pflege von Architekturdokumentation

// end::DE[]

// tag::EN[]
[[LG-04-09]]
==== LG 04-09 [previously LG 3-9]: Know Additional Resources and Tools for Documentation (R3)

Software architects know:

* basics of several published frameworks for the description of software architectures, for example:
** ISO/IEC/IEEE 42010, 
** arc42,
** C4, see <<brownc4>>
* ideas and examples of checklists for the creation, documentation, and review of software architectures
* possible tools for creating and maintaining architectural documentation

// end::EN[]

// tag::TR[]
[[LG-04-09]]
==== LG 04-09 [önceki LG 3-9]: Dokümantasyon İçin Ek Kaynakları ve Araçları Bilmek (R3)

Yazılım mimarları şunları bilir:

* yazılım mimarilerinin tanımı için yayınlanmış çeşitli çerçevelerin temelleri, örneğin:
** ISO/IEC/IEEE 42010,
** arc42,
** C4, bkz. <<brownc4>>
* yazılım mimarilerinin oluşturulması, dokümante edilmesi ve incelenmesi için kontrol listesi fikirleri ve örnekleri
* mimari dokümantasyonu oluşturmak ve sürdürmek için olası araçlar

// end::TR[]

===== {references}
<<iso42010>>, <<arc42>>, <<brownc4>>
